function createfigure(VC)

%  Auto-generated by MATLAB on 30-May-2019 11:06:44
X1 = VC(:,1);
Y1 = (VC(:,2));
X2 = [VC(end,1),VC(1,1)];
Y2 = [VC(end,2),VC(1,2)];



% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',5);

% Create plot
plot(X2,Y2,'LineWidth',5,'Color',[0 0.447058826684952 0.74117648601532]);

% Create scatter
scatter(X1,Y1,'MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[1 0 0],...
    'LineWidth',10);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-4 4]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-4 4]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[0.5 0.5 0.5],'FontSize',18,'XGrid','on',...
    'YGrid','on');
